# mas installs programs from mac app store
#brew "mas"
# install Xcode as prerequisite for macvim
#mas "Xcode", id: 497799835 

brew "git"
brew "macvim"
brew "vim"
brew "python"
brew "python3"
brew "zsh"

cask_args appdir: "~/Applications"
tap "caskroom/cask"
#cask_args caskroom: "~/dotfiles/homebrew/Caskroom"
cask "iterm2"
cask "google-chrome"
cask "firefox"
cask "skim"
cask "spotify"
cask "lastpass"
cask "mactex"
#cask "vlc"
#cask "google-drive"
#cask "dropbox"
