################################################################################
# ZSHENV - Caleb Logemann
################################################################################

# set Path environment variable
PATH=/usr/local/texlive/2017/bin/x86_64-darwin:$PATH
PATH=/usr/local/texlive/2018/bin/x86_64-darwin:$PATH
PATH=/usr/local/texlive/2019/bin/x86_64-darwin:$PATH
PATH=~/dotfiles/bin:$PATH
PATH=/usr/local/opt/python/libexec/bin:$PATH
PATH=/usr/local/bin:$PATH
export PATH

export HOMEBREW_CASK_OPTS='--appdir=~/Applications'

export DOGPACK=~/Documents/Education/Graduate/dogpack-developer
export PYDOGPACK=~/Documents/Education/Graduate/Research/Python/PyDogPack
#export DOGPACK=~/Desktop/dogpack-developer

export PYDOGPACK=~/Documents/Education/Graduate/Research/Python/PyDogPack
